### ISSUE TITLE
Add oauth for reddit API

### ISSUE THREAD

**Issue by rag594** [entranceplus/craw#1]

**Comment by shakdwipeea** [comment]
Is this for user login ? I don't think we need any api for that if we can get the data w/o it.

**Comment by rag594** [comment]
reddit requires OAuth for authentication. If requests are sent simultaneously 429 error code is returned(too many requests). They limited to 240 requests per hour

**Comment by rag594** [comment]
Closing..... Not possible as they restricted their API's access
